version: '2'
services:
    meteringservice-app:
        image: meteringservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://meteringservice-postgresql:5432/meteringservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    meteringservice-postgresql:
        extends:
            file: postgresql.yml
            service: meteringservice-postgresql
