apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteringservice
  annotations:
     "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteringservice
  template:
    metadata:
      labels:
        app: meteringservice
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/path: "/meteringservice/metrics"
         prometheus.io/port: "8080"
         prometheus.io/scrape: "true"
    spec:
      containers:
      - name: meteringservice
        image: meteringservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        - containerPort: 8090
        - containerPort: 8080
        env: 
        - name: JAEGER_SERVICE_NAME
          value: meteringservice
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-collector.observability.svc:14268/api/traces'
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: '1'
        - name: JAEGER_REPORTER_LOG_SPANS
          value: 'true'
        - name: JAEGER_TAGS
          value: 'version=${VERSION}'